# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10C0gxqHa0valrYpCcihJZO6unBLQ91lw
"""

import pickle
import streamlit as st 


pickle_in = open("BankNote.pkl","rb")
classifier=pickle.load(pickle_in)


def predict_note_authentication(variance,skewness,curtosis,entropy):
    prediction=classifier.predict([[variance,skewness,curtosis,entropy]])
    print(prediction)
    return prediction

def main():
    st.title("Diabetes Prediction")
    Glucose = st.text_input("variance")
    Bp = st.text_input("skewness")
    Insulin = st.text_input("curtosis")
    BMI = st.text_input("entropy")
    result=""
    if st.button("Predict"):
        result=predict_note_authentication(variance,skewness,curtosis,entropy)
    st.success('The output is {}'.format(result))
    

if __name__=='__main__':
    main()